{{- $name := .Chart.Name -}}
{{- $version := .Chart.Version -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- range .Values.services }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .host }}
  labels:
    app: "{{ $name }}"
    chart: "{{ $name }}-{{ $version }}"
    release: "{{ $releaseName }}"
    heritage: "{{ $releaseService }}"
subsets:
- addresses:
  {{- range .endpoints }}
  - ip: {{ . }}
  {{- end }}
  ports:
  {{- range .ports }}
  - name: {{ .name }}
    port: {{ .targetPort }}
    protocol: TCP
  {{- end }}
---
{{- end }}
